var localDeviceArr = [
  {
    deviceName: "COLORSTRIKEM",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKE1",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEARRAY1",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 3.63,
    PressureMin: 3.55,
    PressureHoldTime: 30,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEARRAY2",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEARRAY2C",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEARRAY4",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEARRAY4C",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEBOLT1C",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "STRIKEP38",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST1BEAMWASH",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST1LBEAM",
    devicePic: "pics/ROGUEOUTCAST1LBEAM.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST2XWASH",
    devicePic: "pics/ROGUEOUTCAST2XWASH.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST3SPOT",
    devicePic: "pics/ROGUEOUTCAST3SPOT.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST2BEAM",
    devicePic: "pics/ROGUEOUTCAST2BEAM.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST2HYBRID",
    devicePic: "pics/ROGUEOUTCAST2HYBRID.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ROGUEOUTCAST1MBEAM",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "OVATIONE260WWIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: "Not Possible",
    PressureMin: "Not Possible",
    PressureHoldTime: "",
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "OVATIONE910FCIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: "Not Possible",
    PressureMin: "Not Possible",
    PressureHoldTime: "",
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "OVATIONREVEE3IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "OVATIONREVEF3IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "OVATIONREVEP3IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 0.65,
    PressureMin: 0.64,
    PressureHoldTime: 15,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "OVATIONE4WWIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM1SPOT",
    devicePic: "pics/MAVERICKSTORM1SPOT.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM1WASH",
    devicePic: "pics/MAVERICKSTORM1WASH.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM2BEAMWASH",
    devicePic: "pics/MAVERICKSTORM2BEAMWASH.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM2PROFILE",
    devicePic: "pics/MAVERICKSTORM4PROFILE.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM4PROFILE",
    devicePic: "pics/MAVERICKSTORM4PROFILE.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM1HYBRID",
    devicePic: "pics/MAVERICKSTORM1HYBRID.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM1BEAM",
    devicePic: "pics/MAVERICKSTORM1BEAM.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM2PROFILEM",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM4SOLOWASH",
    devicePic: "pics/MAVERICKSTORM4SOLOWASH.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "MAVERICKSTORM3BEAMWASH",
    devicePic: "pics/MAVERICKSTORM3BEAMWASH.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMIPODSL",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMIPODML",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMIPODLL",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMIPANELML",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMIPANELLL",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMILINESL",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ILUMILINEML",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORDASHPARH12IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORDASHPARH7IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORDASHPARH7XIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 30,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORDASHPARH18XIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 30,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORDASHPARH12XIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 30,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORDASHBATTENH12XIP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 30,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO1QUAD",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.23,
    PressureMin: 1.22,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO1QUADZOOM",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO1SOLO",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO2QUADZOOM",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO2SOLO",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO2SOLOVW",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO3SOLO",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOBATTEN72X",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOBATTENQ15",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOMSOLO",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOPANELQ40",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOSOLOBATTEN",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOSOLOBATTEN4",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADO1QS",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 1.31,
    PressureMin: 1.29,
    PressureHoldTime: 10,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOPXLBAR8",
    devicePic: "pics/COLORADOPXLBAR8.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOSOLOBAR1",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOSOLOBAR4",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOSOLOBAR6",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOPXLBAR16",
    devicePic: "pics/COLORADOPXLBAR16",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "COLORADOPXLCURVE12",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 2.18,
    PressureMin: 2.16,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "WELLPAD",
    devicePic: "pics/WELLPAD.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "WELLPanel",
    devicePic: "pics/WELLPANEL.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "EPIXDRIVE2000IP",
    devicePic: "pics/EPIXDRIVE2000IP.png",
    Unit: "psi",
    PressureTarget: 5.80,
    PressureMin: 5.73,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ONAIRPANEL2IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 3.63,
    PressureMin: 3.55,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  },
  {
    deviceName: "ONAIRPANEL1IP",
    devicePic: "pics/placehoder.png",
    Unit: "psi",
    PressureTarget: 3.63,
    PressureMin: 3.55,
    PressureHoldTime: 60,
    VacuumTarget: "0.00",
    VacuumMin: "0.00",
    VacuumHoldTime: 1,
    deviceFrame: [],
    saveTime: ""
  }
];
